version: "1"

mode: resident
interval: "1m"
calendar_id: ja.japanese#holiday@group.v.calendar.google.com
calendar_webhook:
  disable: true
  address: "https://example.com/notify"

handler:
  light:
    start:
      - light_on
    end:
      - light_off

action:
  light_on:
    type: http
    method: POST
    header:
      "User-Agent":
        - "calendar-notifier/v1"
    url: http://localhost/api/v1/light/on
  light_off:
    type: http
    method: POST
    header:
      "User-Agent":
        - "calendar-notifier/v1"
    url: http://localhost/api/v1/light/off
