version: "3.7"
services:
  notifier:
    container_name: calendar-notifier
    image: calendar-notifier
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
    volumes:
      - ./config.yml:/usr/local/etc/calendar-notifier/config.yml:ro
    restart: always
