name: apply

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Published tag (e.g. v1.0.0)"
        required: true

env:
  TERRAFORM_VERSION: 0.14.3

jobs:
  release:
    name: Release
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Set image_tag
        run: |
          tag=$(echo "${{ github.event.inputs.tag }}" | sed "s/^v//")
          if [ -z "$tag" ]; then
            exit 1
          fi
          echo "image_tag = \"$tag\"" >> release.auto.tfvars
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate -no-color
      - name: Apply
        run: terraform apply -no-color
