name: Test on master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REPO: ww24/calendar-notifier
  IMAGE_NAME: calendar-notifier
  IMAGE_TAG: latest

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Install go tools
        run: cat tools.go | grep _ | awk -F '"' '{print $2}' | xargs -tI {} go install {}
      - name: go generate
        run: go generate ./...
      - name: Check uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo "uncommitted changes"
              git status
              exit 1
          fi
      - name: go lint
        run: go list ./... | xargs golint -set_exit_status
      - run: go vet ./...
      - run: go test -v -race ./...

  docker_build_test:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shellcheck
        env:
          SHELLCHECK_OPTS: -e SC2187
        run: find . -name "*.sh" | xargs shellcheck
      - name: Lint
        run: |
          docker run -v $(pwd):/working --rm hadolint/hadolint \
          hadolint /working/Dockerfile \
          --ignore DL3018
      - name: Build docker image
        run: docker build -t "docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" .
      - name: Install trivy
        run: |
          sudo apt-get install --no-install-recommends apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends trivy
      - name: Vulnerability Scan
        run: |
          trivy -q --severity HIGH,CRITICAL --exit-code 1 \
            "docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}"

  docker_push:
    if: ${{ github.event_name == 'push' }}
    needs: test
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
      - name: Build docker image and push (DockerHub)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --output "type=image,push=true" \
            -t "${DOCKER_REPO}":${IMAGE_TAG} .
      - name: Build docker image and push (GitHub)
        run: |
          docker build -t "docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u owner --password-stdin docker.pkg.github.com
          docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}"
